version: '3.8'

services:
#  postgres:
#    image: postgres:15
#    container_name: postgres
#    environment:
#      POSTGRES_DB: shop
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: test415
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    networks:
#      - backend

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test415
    networks:
      - backend

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test415
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
